// <auto-generated />
using System;
using MarketBackend.DataLayer.DatabaseObjects;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarketBackend.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20220624151403_TryingOptionalForeginKeys")]
    partial class TryingOptionalForeginKeys
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Buyers.Carts.DataCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Buyers.Carts.DataProductInBag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("DataShoppingBagId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DataShoppingBagId");

                    b.ToTable("ProductInBags");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Buyers.Carts.DataShoppingBag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("DataCartId")
                        .HasColumnType("int");

                    b.Property<int?>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DataCartId");

                    b.HasIndex("StoreId");

                    b.ToTable("ShoppingBags");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Buyers.DataMember", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("CartId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<int>("Password")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Buyers.DataNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("DataMemberId")
                        .HasColumnType("int");

                    b.Property<string>("Notification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DataMemberId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.DataProduct", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("AmountInInventory")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DataStoreId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PricePerUnit")
                        .HasColumnType("float");

                    b.Property<double>("ProductDiscount")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DataStoreId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.DataProductReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("MemberId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Review")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductReview");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.DataPurchaseOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("DataProductId")
                        .HasColumnType("int");

                    b.Property<int>("PurchaseOption")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DataProductId");

                    b.ToTable("PurchaseOptions");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.DataPurchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BuyerId")
                        .HasColumnType("int");

                    b.Property<int?>("DataMemberId")
                        .HasColumnType("int");

                    b.Property<int?>("DataStore")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PurchaseDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PurchasePrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DataMemberId");

                    b.HasIndex("DataStore");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DataAppointmentsNode", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("DataAppointmentsNodeId")
                        .HasColumnType("int");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DataAppointmentsNodeId");

                    b.ToTable("AppointmentsNodes");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DataBid", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<double>("Bid")
                        .HasColumnType("float");

                    b.Property<bool>("CounterOffer")
                        .HasColumnType("bit");

                    b.Property<int?>("DataStoreId")
                        .HasColumnType("int");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<double>("Offer")
                        .HasColumnType("float");

                    b.Property<int>("ProdctId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DataStoreId");

                    b.ToTable("Bids");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DataBidMemberId", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("DataBidId")
                        .HasColumnType("int");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DataBidId");

                    b.ToTable("DataBidMemberId");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DataManagerPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("DataStoreMemberRolesId")
                        .HasColumnType("int");

                    b.Property<int?>("Permission")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DataStoreMemberRolesId");

                    b.ToTable("ManagerPermissions");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DataStore", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("AppointmentsId")
                        .HasColumnType("int");

                    b.Property<int?>("DiscountManagerId")
                        .HasColumnType("int");

                    b.Property<int?>("FounderId")
                        .HasColumnType("int");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PurchaseManagerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentsId");

                    b.HasIndex("DiscountManagerId");

                    b.HasIndex("FounderId");

                    b.HasIndex("PurchaseManagerId");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DataStoreMemberRoles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int?>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("StoreMemberRoles");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DiscountPolicy.DataDiscount", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("DataStoreDiscountPolicyManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DiscountExpressionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DataStoreDiscountPolicyManagerId");

                    b.HasIndex("DiscountExpressionId");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DiscountPolicy.DataExpression", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Expressions");

                    b.HasDiscriminator<string>("Discriminator").HasValue("DataExpression");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DiscountPolicy.DataStoreDiscountPolicyManager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("DataStoreDiscountPolicyManager");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DiscountPolicy.DiscountInterfaces.DataPredicateExpression", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DiscountPredicateExpressions");

                    b.HasDiscriminator<string>("Discriminator").HasValue("DataPredicateExpression");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.PurchasesPolicy.DataPurchasePolicy", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("DataStorePurchasePolicyManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PolicyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DataStorePurchasePolicyManagerId");

                    b.HasIndex("PolicyId");

                    b.ToTable("PurchasePolicies");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.PurchasesPolicy.DataStorePurchasePolicyManager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("DataStorePurchasePolicyManager");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.PurchasesPolicy.PurchasesInterfaces.DataIPurchasePolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InterfacesPurchasePolicies");

                    b.HasDiscriminator<string>("Discriminator").HasValue("DataIPurchasePolicy");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.PurchasesPolicy.PurchasesInterfaces.DataPredicateExpression", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PruchasePredicateExpressions");

                    b.HasDiscriminator<string>("Discriminator").HasValue("DataPredicateExpression");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DiscountPolicy.DiscountExpressions.DataConditionDiscount", b =>
                {
                    b.HasBaseType("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DiscountPolicy.DataExpression");

                    b.Property<int?>("DiscountExpressionId")
                        .HasColumnType("int");

                    b.Property<int?>("PredicateId")
                        .HasColumnType("int");

                    b.HasIndex("DiscountExpressionId");

                    b.HasIndex("PredicateId");

                    b.HasDiscriminator().HasValue("DataConditionDiscount");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DiscountPolicy.DiscountExpressions.DataIfDiscount", b =>
                {
                    b.HasBaseType("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DiscountPolicy.DataExpression");

                    b.Property<int?>("ElseId")
                        .HasColumnType("int");

                    b.Property<int?>("TestId")
                        .HasColumnType("int");

                    b.Property<int?>("ThenId")
                        .HasColumnType("int");

                    b.HasIndex("ElseId");

                    b.HasIndex("TestId");

                    b.HasIndex("ThenId");

                    b.HasDiscriminator().HasValue("DataIfDiscount");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DiscountPolicy.DiscountExpressions.DataLogicalExpression", b =>
                {
                    b.HasBaseType("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DiscountPolicy.DiscountInterfaces.DataPredicateExpression");

                    b.Property<int?>("FirstId")
                        .HasColumnType("int");

                    b.Property<int?>("SecondId")
                        .HasColumnType("int");

                    b.HasIndex("FirstId");

                    b.HasIndex("SecondId");

                    b.HasDiscriminator().HasValue("DataLogicalExpression");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DiscountPolicy.DiscountExpressions.PredicatesExpressions.DataBagValuePredicate", b =>
                {
                    b.HasBaseType("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DiscountPolicy.DiscountInterfaces.DataPredicateExpression");

                    b.Property<int>("Worth")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("DataBagValuePredicate");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DiscountPolicy.DiscountExpressions.PredicatesExpressions.DataProductAmountPredicate", b =>
                {
                    b.HasBaseType("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DiscountPolicy.DiscountInterfaces.DataPredicateExpression");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("DataProductAmountPredicate");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DiscountPolicy.DiscountInterfaces.DataDiscountExpression", b =>
                {
                    b.HasBaseType("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DiscountPolicy.DataExpression");

                    b.Property<int?>("DataMaxExpressionId")
                        .HasColumnType("int");

                    b.HasIndex("DataMaxExpressionId");

                    b.HasDiscriminator().HasValue("DataDiscountExpression");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.PurchasesPolicy.LogicalOperators.DataAndExpression", b =>
                {
                    b.HasBaseType("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.PurchasesPolicy.PurchasesInterfaces.DataIPurchasePolicy");

                    b.Property<int?>("FirstPredId")
                        .HasColumnType("int")
                        .HasColumnName("DataAndExpression_FirstPredId");

                    b.Property<int?>("SecondPredId")
                        .HasColumnType("int")
                        .HasColumnName("DataAndExpression_SecondPredId");

                    b.HasIndex("FirstPredId");

                    b.HasIndex("SecondPredId");

                    b.HasDiscriminator().HasValue("DataAndExpression");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.PurchasesPolicy.LogicalOperators.DataImpliesExpression", b =>
                {
                    b.HasBaseType("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.PurchasesPolicy.PurchasesInterfaces.DataIPurchasePolicy");

                    b.Property<int?>("AllowingId")
                        .HasColumnType("int");

                    b.Property<int?>("ConditionId")
                        .HasColumnType("int");

                    b.HasIndex("AllowingId");

                    b.HasIndex("ConditionId");

                    b.HasDiscriminator().HasValue("DataImpliesExpression");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.PurchasesPolicy.LogicalOperators.DataOrExpression", b =>
                {
                    b.HasBaseType("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.PurchasesPolicy.PurchasesInterfaces.DataIPurchasePolicy");

                    b.Property<int?>("FirstPredId")
                        .HasColumnType("int");

                    b.Property<int?>("SecondPredId")
                        .HasColumnType("int");

                    b.HasIndex("FirstPredId");

                    b.HasIndex("SecondPredId");

                    b.HasDiscriminator().HasValue("DataOrExpression");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.PurchasesPolicy.PredicatePolicies.DataCheckProductLessPredicate", b =>
                {
                    b.HasBaseType("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.PurchasesPolicy.PurchasesInterfaces.DataPredicateExpression");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("DataCheckProductLessPredicate");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.PurchasesPolicy.PurchasesInterfaces.DataRestrictionExpression", b =>
                {
                    b.HasBaseType("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.PurchasesPolicy.PurchasesInterfaces.DataIPurchasePolicy");

                    b.HasDiscriminator().HasValue("DataRestrictionExpression");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DiscountPolicy.DiscountExpressions.BasicDiscounts.DataStoreDiscount", b =>
                {
                    b.HasBaseType("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DiscountPolicy.DiscountInterfaces.DataDiscountExpression");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("DataStoreDiscount");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DiscountPolicy.DiscountExpressions.LogicalExpressions.DataAndExpression", b =>
                {
                    b.HasBaseType("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DiscountPolicy.DiscountExpressions.DataLogicalExpression");

                    b.HasDiscriminator().HasValue("DataAndExpression");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DiscountPolicy.DiscountExpressions.LogicalExpressions.DataOrExpression", b =>
                {
                    b.HasBaseType("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DiscountPolicy.DiscountExpressions.DataLogicalExpression");

                    b.HasDiscriminator().HasValue("DataOrExpression");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DiscountPolicy.DiscountExpressions.LogicalExpressions.DataXorExpression", b =>
                {
                    b.HasBaseType("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DiscountPolicy.DiscountExpressions.DataLogicalExpression");

                    b.HasDiscriminator().HasValue("DataXorExpression");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DiscountPolicy.DiscountExpressions.NumericExpressions.DataMaxExpression", b =>
                {
                    b.HasBaseType("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DiscountPolicy.DiscountInterfaces.DataDiscountExpression");

                    b.HasDiscriminator().HasValue("DataMaxExpression");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.PurchasesPolicy.PredicatePolicies.DataCheckProductMoreEqualsPredicate", b =>
                {
                    b.HasBaseType("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.PurchasesPolicy.PredicatePolicies.DataCheckProductLessPredicate");

                    b.HasDiscriminator().HasValue("DataCheckProductMoreEqualsPredicate");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.PurchasesPolicy.RestrictionPolicies.DataAfterHourRestriction", b =>
                {
                    b.HasBaseType("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.PurchasesPolicy.PurchasesInterfaces.DataRestrictionExpression");

                    b.Property<int>("Hour")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("DataAfterHourRestriction");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.PurchasesPolicy.RestrictionPolicies.DataAtLeastAmountRestriction", b =>
                {
                    b.HasBaseType("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.PurchasesPolicy.PurchasesInterfaces.DataRestrictionExpression");

                    b.Property<int>("Amount")
                        .HasColumnType("int")
                        .HasColumnName("DataAtLeastAmountRestriction_Amount");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("DataAtLeastAmountRestriction_ProductId");

                    b.HasDiscriminator().HasValue("DataAtLeastAmountRestriction");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.PurchasesPolicy.RestrictionPolicies.DataDateRestriction", b =>
                {
                    b.HasBaseType("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.PurchasesPolicy.PurchasesInterfaces.DataRestrictionExpression");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("DataDateRestriction");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DiscountPolicy.DiscountExpressions.BasicDiscounts.DataDateDiscount", b =>
                {
                    b.HasBaseType("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DiscountPolicy.DiscountExpressions.BasicDiscounts.DataStoreDiscount");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("DataDateDiscount");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DiscountPolicy.DiscountExpressions.BasicDiscounts.DataOneProductDiscount", b =>
                {
                    b.HasBaseType("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DiscountPolicy.DiscountExpressions.BasicDiscounts.DataStoreDiscount");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("DataOneProductDiscount");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.PurchasesPolicy.RestrictionPolicies.DataAfterHourProductRestriction", b =>
                {
                    b.HasBaseType("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.PurchasesPolicy.RestrictionPolicies.DataAfterHourRestriction");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("DataAfterHourProductRestriction");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.PurchasesPolicy.RestrictionPolicies.DataAtMostAmountRestriction", b =>
                {
                    b.HasBaseType("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.PurchasesPolicy.RestrictionPolicies.DataAtLeastAmountRestriction");

                    b.HasDiscriminator().HasValue("DataAtMostAmountRestriction");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.PurchasesPolicy.RestrictionPolicies.DataBeforeHourRestriction", b =>
                {
                    b.HasBaseType("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.PurchasesPolicy.RestrictionPolicies.DataAfterHourRestriction");

                    b.HasDiscriminator().HasValue("DataBeforeHourRestriction");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.PurchasesPolicy.RestrictionPolicies.DataBeforeHourProductRestriction", b =>
                {
                    b.HasBaseType("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.PurchasesPolicy.RestrictionPolicies.DataBeforeHourRestriction");

                    b.Property<int>("Amount")
                        .HasColumnType("int")
                        .HasColumnName("DataBeforeHourProductRestriction_Amount");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("DataBeforeHourProductRestriction_ProductId");

                    b.HasDiscriminator().HasValue("DataBeforeHourProductRestriction");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Buyers.Carts.DataProductInBag", b =>
                {
                    b.HasOne("MarketBackend.DataLayer.DataDTOs.Buyers.Carts.DataShoppingBag", null)
                        .WithMany("ProductsAmounts")
                        .HasForeignKey("DataShoppingBagId");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Buyers.Carts.DataShoppingBag", b =>
                {
                    b.HasOne("MarketBackend.DataLayer.DataDTOs.Buyers.Carts.DataCart", null)
                        .WithMany("ShoppingBags")
                        .HasForeignKey("DataCartId");

                    b.HasOne("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DataStore", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Buyers.DataMember", b =>
                {
                    b.HasOne("MarketBackend.DataLayer.DataDTOs.Buyers.Carts.DataCart", "Cart")
                        .WithMany()
                        .HasForeignKey("CartId");

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Buyers.DataNotification", b =>
                {
                    b.HasOne("MarketBackend.DataLayer.DataDTOs.Buyers.DataMember", null)
                        .WithMany("PendingNotifications")
                        .HasForeignKey("DataMemberId");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.DataProduct", b =>
                {
                    b.HasOne("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DataStore", null)
                        .WithMany("Products")
                        .HasForeignKey("DataStoreId");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.DataProductReview", b =>
                {
                    b.HasOne("MarketBackend.DataLayer.DataDTOs.Buyers.DataMember", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId");

                    b.HasOne("MarketBackend.DataLayer.DataDTOs.DataProduct", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId");

                    b.Navigation("Member");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.DataPurchaseOption", b =>
                {
                    b.HasOne("MarketBackend.DataLayer.DataDTOs.DataProduct", null)
                        .WithMany("PurchaseOptions")
                        .HasForeignKey("DataProductId");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.DataPurchase", b =>
                {
                    b.HasOne("MarketBackend.DataLayer.DataDTOs.Buyers.DataMember", null)
                        .WithMany("PurchaseHistory")
                        .HasForeignKey("DataMemberId");

                    b.HasOne("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DataStore", "Store")
                        .WithMany("PurchaseHistory")
                        .HasForeignKey("DataStore");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DataAppointmentsNode", b =>
                {
                    b.HasOne("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DataAppointmentsNode", null)
                        .WithMany("Children")
                        .HasForeignKey("DataAppointmentsNodeId");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DataBid", b =>
                {
                    b.HasOne("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DataStore", null)
                        .WithMany("Bids")
                        .HasForeignKey("DataStoreId");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DataBidMemberId", b =>
                {
                    b.HasOne("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DataBid", null)
                        .WithMany("Approving")
                        .HasForeignKey("DataBidId");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DataManagerPermission", b =>
                {
                    b.HasOne("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DataStoreMemberRoles", null)
                        .WithMany("ManagerPermissions")
                        .HasForeignKey("DataStoreMemberRolesId");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DataStore", b =>
                {
                    b.HasOne("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DataAppointmentsNode", "Appointments")
                        .WithMany()
                        .HasForeignKey("AppointmentsId");

                    b.HasOne("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DiscountPolicy.DataStoreDiscountPolicyManager", "DiscountManager")
                        .WithMany()
                        .HasForeignKey("DiscountManagerId");

                    b.HasOne("MarketBackend.DataLayer.DataDTOs.Buyers.DataMember", "Founder")
                        .WithMany()
                        .HasForeignKey("FounderId");

                    b.HasOne("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.PurchasesPolicy.DataStorePurchasePolicyManager", "PurchaseManager")
                        .WithMany()
                        .HasForeignKey("PurchaseManagerId");

                    b.Navigation("Appointments");

                    b.Navigation("DiscountManager");

                    b.Navigation("Founder");

                    b.Navigation("PurchaseManager");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DataStoreMemberRoles", b =>
                {
                    b.HasOne("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DataStore", "Store")
                        .WithMany("MembersPermissions")
                        .HasForeignKey("StoreId");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DiscountPolicy.DataDiscount", b =>
                {
                    b.HasOne("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DiscountPolicy.DataStoreDiscountPolicyManager", null)
                        .WithMany("Discounts")
                        .HasForeignKey("DataStoreDiscountPolicyManagerId");

                    b.HasOne("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DiscountPolicy.DataExpression", "DiscountExpression")
                        .WithMany()
                        .HasForeignKey("DiscountExpressionId");

                    b.Navigation("DiscountExpression");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.PurchasesPolicy.DataPurchasePolicy", b =>
                {
                    b.HasOne("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.PurchasesPolicy.DataStorePurchasePolicyManager", null)
                        .WithMany("PurchasesPolicies")
                        .HasForeignKey("DataStorePurchasePolicyManagerId");

                    b.HasOne("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.PurchasesPolicy.PurchasesInterfaces.DataIPurchasePolicy", "Policy")
                        .WithMany()
                        .HasForeignKey("PolicyId");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DiscountPolicy.DiscountExpressions.DataConditionDiscount", b =>
                {
                    b.HasOne("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DiscountPolicy.DiscountInterfaces.DataDiscountExpression", "DiscountExpression")
                        .WithMany()
                        .HasForeignKey("DiscountExpressionId");

                    b.HasOne("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DiscountPolicy.DiscountInterfaces.DataPredicateExpression", "Predicate")
                        .WithMany()
                        .HasForeignKey("PredicateId");

                    b.Navigation("DiscountExpression");

                    b.Navigation("Predicate");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DiscountPolicy.DiscountExpressions.DataIfDiscount", b =>
                {
                    b.HasOne("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DiscountPolicy.DiscountInterfaces.DataDiscountExpression", "Else")
                        .WithMany()
                        .HasForeignKey("ElseId");

                    b.HasOne("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DiscountPolicy.DiscountInterfaces.DataPredicateExpression", "Test")
                        .WithMany()
                        .HasForeignKey("TestId");

                    b.HasOne("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DiscountPolicy.DiscountInterfaces.DataDiscountExpression", "Then")
                        .WithMany()
                        .HasForeignKey("ThenId");

                    b.Navigation("Else");

                    b.Navigation("Test");

                    b.Navigation("Then");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DiscountPolicy.DiscountExpressions.DataLogicalExpression", b =>
                {
                    b.HasOne("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DiscountPolicy.DiscountInterfaces.DataPredicateExpression", "First")
                        .WithMany()
                        .HasForeignKey("FirstId");

                    b.HasOne("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DiscountPolicy.DiscountInterfaces.DataPredicateExpression", "Second")
                        .WithMany()
                        .HasForeignKey("SecondId");

                    b.Navigation("First");

                    b.Navigation("Second");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DiscountPolicy.DiscountInterfaces.DataDiscountExpression", b =>
                {
                    b.HasOne("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DiscountPolicy.DiscountExpressions.NumericExpressions.DataMaxExpression", null)
                        .WithMany("Discounts")
                        .HasForeignKey("DataMaxExpressionId");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.PurchasesPolicy.LogicalOperators.DataAndExpression", b =>
                {
                    b.HasOne("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.PurchasesPolicy.PurchasesInterfaces.DataRestrictionExpression", "FirstPred")
                        .WithMany()
                        .HasForeignKey("FirstPredId");

                    b.HasOne("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.PurchasesPolicy.PurchasesInterfaces.DataRestrictionExpression", "SecondPred")
                        .WithMany()
                        .HasForeignKey("SecondPredId");

                    b.Navigation("FirstPred");

                    b.Navigation("SecondPred");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.PurchasesPolicy.LogicalOperators.DataImpliesExpression", b =>
                {
                    b.HasOne("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.PurchasesPolicy.PurchasesInterfaces.DataPredicateExpression", "Allowing")
                        .WithMany()
                        .HasForeignKey("AllowingId");

                    b.HasOne("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.PurchasesPolicy.PurchasesInterfaces.DataPredicateExpression", "Condition")
                        .WithMany()
                        .HasForeignKey("ConditionId");

                    b.Navigation("Allowing");

                    b.Navigation("Condition");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.PurchasesPolicy.LogicalOperators.DataOrExpression", b =>
                {
                    b.HasOne("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.PurchasesPolicy.PurchasesInterfaces.DataRestrictionExpression", "FirstPred")
                        .WithMany()
                        .HasForeignKey("FirstPredId");

                    b.HasOne("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.PurchasesPolicy.PurchasesInterfaces.DataRestrictionExpression", "SecondPred")
                        .WithMany()
                        .HasForeignKey("SecondPredId");

                    b.Navigation("FirstPred");

                    b.Navigation("SecondPred");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Buyers.Carts.DataCart", b =>
                {
                    b.Navigation("ShoppingBags");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Buyers.Carts.DataShoppingBag", b =>
                {
                    b.Navigation("ProductsAmounts");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Buyers.DataMember", b =>
                {
                    b.Navigation("PendingNotifications");

                    b.Navigation("PurchaseHistory");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.DataProduct", b =>
                {
                    b.Navigation("PurchaseOptions");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DataAppointmentsNode", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DataBid", b =>
                {
                    b.Navigation("Approving");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DataStore", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("MembersPermissions");

                    b.Navigation("Products");

                    b.Navigation("PurchaseHistory");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DataStoreMemberRoles", b =>
                {
                    b.Navigation("ManagerPermissions");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DiscountPolicy.DataStoreDiscountPolicyManager", b =>
                {
                    b.Navigation("Discounts");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.PurchasesPolicy.DataStorePurchasePolicyManager", b =>
                {
                    b.Navigation("PurchasesPolicies");
                });

            modelBuilder.Entity("MarketBackend.DataLayer.DataDTOs.Market.StoreManagement.DiscountPolicy.DiscountExpressions.NumericExpressions.DataMaxExpression", b =>
                {
                    b.Navigation("Discounts");
                });
#pragma warning restore 612, 618
        }
    }
}
