name: .NET

on:
  push:
    branches:
      - main
      - develop
      - 'Tests/**'
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    name: Build 
    runs-on: windows-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
      DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: false
      DOTNET_MULTILEVEL_LOOKUP: 0
      DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: true
      TERM: xterm

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x

    - name: Restore
      run: dotnet restore ./Server/MarketBackend

    - name: Build
      run: dotnet build --configuration Release --no-restore ./Server/MarketBackend

    - name: Test
      run: dotnet test ./Server/MarketBackend/TestMarketBackend
